apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: job-webserver
spec:
  replicas: 5
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: job-webserver
    spec:
      serviceAccountName: serviceaccount-name
      containers:
      - name: job-webserver
        image: 806928298771.dkr.ecr.us-east-1.amazonaws.com/joxylogic-k8s/job_webserver:latest
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command: ["curl", "localhost:4000/shutdown"]
        livenessProbe:
          httpGet:
            path: /healthz
            port: 4000
          initialDelaySeconds: 20
          timeoutSeconds: 5        
        ports:
        - containerPort: 4000
        args: ["foreground"]
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: MY_POD_NAMESPACE
          value: prod
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name