apiVersion: v1
kind: Service
metadata:
  name: local-db-svc
spec:
  selector:
    app: local-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 32003
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-db
spec:
  selector:
    matchLabels:
      app: local-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: local-db
    spec:
      containers:
      - name: local-db
        image: mysql:5.7.23
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysql
        ports:
        - containerPort: 3306
          name: local-db
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-persist
      volumes:
      - name: mysql-persist
        persistentVolumeClaim:
          claimName: mysql-pv-claim
